version: "3"
services:
  nginx:
    ports:
     - "3000:80"
  node-app-container2:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app # Anonymous volume
      - /app/node_modules # Anonymous volume
    environment:
      - NODE_ENV=development
      - MONGO_USER=sparkyk
      - MONGO_PASSWORD=password
      - SESSION_SECRET=secret
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sparkyk
      - MONGO_INITDB_ROOT_PASSWORD=password